#homepage:
#    path: /
#    defaults: { _controller: 'AppBundle:Homepage:index' }
#
#add:
#    path: /add
#    defaults: { _controller: 'AppBundle:Media:add' }
#
#movies:
#    path: /movies
#    defaults: { _controller: 'AppBundle:Media:showAllMovies' }

#series:
#    path: /series
#    defaults: { _controller: 'AppBundle:Media:showAllSeries' }